# Generated by Django 4.0.6 on 2023-03-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('sender', models.CharField(max_length=500)),
                ('idNo', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('senderTel', models.CharField(max_length=500)),
                ('porpuse', models.CharField(max_length=500)),
            ],
        ),
    ]
