# Generated by Django 4.0.6 on 2023-03-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_createpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpdf',
            name='idNo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='createpdf',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='createpdf',
            name='time',
            field=models.TimeField(blank=True, default='14:01:29'),
        ),
    ]
