# Generated by Django 4.0.6 on 2023-03-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_createpdf_idno_alter_createpdf_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpdf',
            name='time',
            field=models.TimeField(blank=True, default='14:16:41'),
        ),
        migrations.AlterField(
            model_name='createpdf',
            name='valueDate',
            field=models.CharField(blank=True, default='03/13/23', max_length=50),
        ),
    ]
