# Generated by Django 4.0.6 on 2023-03-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_beneficiary_delete_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpdf',
            name='time',
            field=models.TimeField(blank=True, default='14:43:13'),
        ),
    ]
