# Generated by Django 4.1.7 on 2023-03-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_createpdf_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpdf',
            name='time',
            field=models.TimeField(blank=True, default='15:38:59'),
        ),
    ]
