# Generated by Django 4.0.6 on 2023-03-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_createpdf_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpdf',
            name='time',
            field=models.TimeField(blank=True, default='16:50:44'),
        ),
    ]
