# Generated by Django 4.0.6 on 2023-03-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_createpdf_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('accNo', models.AutoField(primary_key=True, serialize=False)),
                ('byOrder', models.CharField(max_length=500)),
                ('receiverNo', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('nationality', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='CreatePdf',
        ),
    ]
