# Generated by Django 4.1.7 on 2023-04-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_beneficiary_delete_createpdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('senderNo', models.CharField(max_length=200)),
                ('idNo', models.CharField(max_length=500)),
                ('porpuse', models.CharField(max_length=500)),
                ('payoutAmtUsd', models.CharField(max_length=500)),
                ('rate', models.CharField(max_length=500)),
                ('charge', models.CharField(blank=True, default=0, max_length=500)),
                ('password', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
