# Generated by Django 4.0.6 on 2023-04-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_receipt_remove_sender_charge_remove_sender_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='time',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='valueDate',
            field=models.CharField(max_length=500),
        ),
    ]
